# -*- coding: utf-8 -*-
"""Credit Card Fraud Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U8fsUMzWtfhE8xUMJxtmBSzQOHX06-tb
"""

import numpy as numpy
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

credit_card_data = pd.read_csv("/content/creditcard.csv")

credit_card_data.head(10)

credit_card_data.tail(10)

credit_card_data.info()

credit_card_data.isnull().sum()

credit_card_data["Class"].value_counts()

legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

print(legit.shape)
print(fraud.shape)

legit.head(5)

fraud.head(5)

legit.Amount.describe()

fraud.Amount.describe()

credit_card_data.groupby("Class").mean()

legit_sample = legit.sample(n=492)

new_dataset = pd.concat([legit_sample,fraud], axis=0)

new_dataset.head(5)

new_dataset.shape

new_dataset["Class"].value_counts()

new_dataset.groupby("Class").mean()

X = new_dataset.drop(columns="Class",axis=1)
Y = new_dataset["Class"]

print(X)

print(Y)

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

model = LogisticRegression()

model.fit(X_train,Y_train)

X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction,Y_train)

print("Accuracy on Training Data : ", training_data_accuracy)

training_data_f1_score = f1_score(X_train_prediction,Y_train)

print("F1 Score on Training Data : ", training_data_f1_score)

training_data_confusion_matrix = confusion_matrix(X_train_prediction,Y_train)

print("Confusion Matrix on Training Data : ", training_data_confusion_matrix)

training_data_classification_report = classification_report(X_train_prediction,Y_train)

print("Classification Report on Training Data : ", training_data_classification_report)

X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction,Y_test)

print("Accuracy on Test Data : ", test_data_accuracy)

test_data_f1_score = f1_score(X_test_prediction,Y_test)

print("F1 Score on Test Data : ", test_data_f1_score)

test_data_confusion_matrix = confusion_matrix(X_test_prediction,Y_test)

print("Confusion Matrix on Test Data : ", test_data_confusion_matrix)

test_data_classification_report = classification_report(X_test_prediction,Y_test)

print("Classification Report on Test Data : ", test_data_classification_report)

